### ISSUE TITLE
[bitnami/magento] Installation not moving past Install Script or Reindexing

### ISSUE THREAD

**Issue by bastianhilton** [bitnami/containers#55198] opened 2024-01-20 06:19 UTC
### Name and Version

bitnami/magento2.4.6

### What architecture are you using?

arm64

### What steps will reproduce the bug?

Download magento bitnami/magento image
add in environmental variables
run docker 

### What is the expected behavior?

for magento to be installed via docker

### What do you see instead?

![image](https://github.com/bitnami/containers/assets/16978186/f1f69f7f-7166-489d-90a4-e19bcc726094)

### Additional information

I have been attempting to run this docker image for days and still same issue, i'm on Ubuntu 22.04 + Docker on Hostinger, I have the docker image connected to AWS RDS for Mysql and a docker install of Elasticsearch. Am I missing something?

**Comment by bastianhilton** [comment] 2024-01-21 03:22
so it seems with BITNAMI_DEBUG = "TRUE" it appears i have more information, the installation keeps restarting at trying to connect to elasticsearch

[Progress: 1311 / 1323]
Module 'Magento_Wishlist':
[Progress: 1312 / 1323]
Module 'Magento_WishlistAnalytics':
[Progress: 1313 / 1323]
Module 'Magento_WishlistGraphQl':
[Progress: 1314 / 1323]
Module 'PayPal_Braintree':
[Progress: 1315 / 1323]
Module 'PayPal_BraintreeGraphQl':
[Progress: 1316 / 1323]
Module 'Temando_ShippingRemover':
[Progress: 1317 / 1323]
Enabling caches:
Current status:

1
block_html: 1

full_page: 1
[Progress: 1318 / 1323]
Installing admin user...
[Progress: 1319 / 1323]
Caches clearing:
Cache cleared successfully
[Progress: 1320 / 1323]
Disabling Maintenance Mode:
[Progress: 1321 / 1323]
Post installation file permissions check...
For security, remove write permissions from these directories: '/opt/bitnami/magento/app/etc'
[Progress: 1322 / 1323]
Write installation date...
[Progress: 1323 / 1323]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Nothing to import.
magento 03:15:54.25 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_frontend' to '0'
Value was saved.
magento 03:16:06.02 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_adminhtml' to '0'
Value was saved.
magento 03:16:10.21 DEBUG ==> Setting Magento configuration value 'web/secure/base_url' to 'https://localhost/'
Value was saved.
magento 03:16:14.45 DEBUG ==> Setting Magento configuration value 'web/unsecure/base_url' to 'http://localhost/'
Value was saved.
magento 03:16:18.79 DEBUG ==> Setting Magento configuration value 'web/seo/use_rewrites' to '1'
Value was saved.
No modules were changed.
No modules were changed.
Enabled default mode.
magento 03:16:29.75 INFO  ==> Reindexing
Design Config Grid index has been rebuilt successfully in 00:00:01
Customer Grid index has been rebuilt successfully in 00:00:02
Category Products index has been rebuilt successfully in 00:00:10
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:05
Product EAV index has been rebuilt successfully in 00:00:04
Stock index has been rebuilt successfully in 00:00:06
Inventory index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:08
Catalog Search index process error during indexation process:
error=no handler found for uri [/magento2_product_1_v2/document/_mapping?include_type_name=true] and method [PUT]
magento 03:17:27.58 INFO  ==> 
magento 03:17:27.59 INFO  ==> Welcome to the Bitnami magento container
magento 03:17:27.59 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
magento 03:17:27.59 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
magento 03:17:27.59 INFO  ==> 
magento 03:17:27.59 INFO  ==> ** Starting Magento setup **
magento 03:17:27.61 DEBUG ==> Validating settings in APACHE_* environment variables
realpath: /bitnami/apache/conf: No such file or directory
magento 03:17:27.63 INFO  ==> Configuring the HTTP port
magento 03:17:27.63 DEBUG ==> Configuring port 8094 on file /opt/bitnami/apache/conf/httpd.conf
magento 03:17:27.64 DEBUG ==> Configuring port 8094 on file /opt/bitnami/apache/conf/bitnami/bitnami.conf
magento 03:17:27.64 DEBUG ==> Configuring port 8094 on file /opt/bitnami/apache/conf/vhosts/00_status-vhost.conf
magento 03:17:27.65 INFO  ==> Configuring the HTTPS port
magento 03:17:27.65 DEBUG ==> Configuring port 9443 on file /opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
magento 03:17:27.65 INFO  ==> Configuring Apache ServerTokens directive
magento 03:17:27.65 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
magento 03:17:27.68 INFO  ==> Configuring PHP options
magento 03:17:27.68 INFO  ==> Setting PHP expose_php option
magento 03:17:27.68 INFO  ==> Setting PHP output_buffering option
magento 03:17:27.70 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
magento 03:17:27.72 DEBUG ==> Validating settings in MAGENTO_* environment variables...
magento 03:17:27.80 INFO  ==> Ensuring Magento directories exist
magento 03:17:27.80 INFO  ==> Configuring permissions
magento 03:17:27.81 INFO  ==> Trying to connect to the database server
magento 03:17:27.82 DEBUG ==> Executing SQL command:
SELECT 1
1
magento 03:17:28.32 INFO  ==> Trying to connect to Elasticsearch
magento 03:17:28.33 INFO  ==> Running Magento install script
Starting Magento installation:
File permissions check...
[Progress: 1 / 1323]
Required extensions check...
[Progress: 2 / 1323]
Enabling Maintenance Mode...
[Progress: 3 / 1323]
Installing deployment configuration...
[Progress: 4 / 1323]
Installing database schema:
Schema creation/updates:

**Comment by javsalgar** [comment] 2024-01-22 08:26
Hi!

Does the issue occur with, for example, a connection with a MariaDB docker instance? It seems to me that the issue is related to RDS but I would like to confirm it.

**Comment by bastianhilton** [comment] 2024-01-22 23:16
I can try it with a MariaDB docker instance, but currently its connected to a RDS instance.

**Comment by bastianhilton** [comment] 2024-01-23 00:00
with a local mariadb docker instance, it continues to loop through the same steps:

[Progress: 1285 / 1323]
Module 'Magento_SwaggerWebapi':
[Progress: 1286 / 1323]
Module 'Magento_SwaggerWebapiAsync':
[Progress: 1287 / 1323]
Module 'Magento_Swatches':
[Progress: 1288 / 1323]
Module 'Magento_SwatchesGraphQl':
[Progress: 1289 / 1323]
Module 'Magento_SwatchesLayeredNavigation':
[Progress: 1290 / 1323]
Module 'Magento_Tax':
[Progress: 1291 / 1323]
Module 'Magento_TaxGraphQl':
[Progress: 1292 / 1323]
Module 'Magento_TaxImportExport':
[Progress: 1293 / 1323]
Module 'Magento_ThemeGraphQl':
[Progress: 1294 / 1323]
Module 'Magento_Translation':
[Progress: 1295 / 1323]
Module 'Magento_GoogleOptimizer':
[Progress: 1296 / 1323]
Module 'Magento_Ups':
[Progress: 1297 / 1323]
Module 'Magento_SampleData':
[Progress: 1298 / 1323]
Module 'Magento_CatalogUrlRewriteGraphQl':
[Progress: 1299 / 1323]
Module 'Magento_AsynchronousOperations':
[Progress: 1300 / 1323]
Module 'Magento_Usps':
[Progress: 1301 / 1323]
Module 'Magento_InventoryConfigurableProductFrontendUi':
[Progress: 1302 / 1323]
Module 'Magento_PaypalCaptcha':
[Progress: 1303 / 1323]
Module 'Magento_VaultGraphQl':
[Progress: 1304 / 1323]
Module 'Magento_Version':
[Progress: 1305 / 1323]
Module 'Magento_InventoryInStorePickupWebapiExtension':
[Progress: 1306 / 1323]
Module 'Magento_WebapiAsync':
[Progress: 1307 / 1323]
Module 'Magento_WebapiSecurity':
[Progress: 1308 / 1323]
Module 'Magento_Weee':
[Progress: 1309 / 1323]
Module 'Magento_WeeeGraphQl':
[Progress: 1310 / 1323]
Module 'Magento_CurrencySymbol':
[Progress: 1311 / 1323]
Module 'Magento_Wishlist':
[Progress: 1312 / 1323]
Module 'Magento_WishlistAnalytics':
[Progress: 1313 / 1323]
Module 'Magento_WishlistGraphQl':
[Progress: 1314 / 1323]
Module 'PayPal_Braintree':
[Progress: 1315 / 1323]
Module 'PayPal_BraintreeGraphQl':
[Progress: 1316 / 1323]
Module 'Temando_ShippingRemover':
[Progress: 1317 / 1323]
Enabling caches:
Current status:

1
block_html: 1

full_page: 1
[Progress: 1318 / 1323]
Installing admin user...
[Progress: 1319 / 1323]
Caches clearing:
Cache cleared successfully
[Progress: 1320 / 1323]
Disabling Maintenance Mode:
[Progress: 1321 / 1323]
Post installation file permissions check...
For security, remove write permissions from these directories: '/opt/bitnami/magento/app/etc'
[Progress: 1322 / 1323]
Write installation date...
[Progress: 1323 / 1323]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Nothing to import.
magento 23:59:21.93 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_frontend' to '0'
Value was saved.
magento 23:59:28.89 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_adminhtml' to '0'
Value was saved.
magento 23:59:29.87 DEBUG ==> Setting Magento configuration value 'web/secure/base_url' to 'https://localhost/'
Value was saved.
magento 23:59:30.87 DEBUG ==> Setting Magento configuration value 'web/unsecure/base_url' to 'http://localhost/'
Value was saved.
magento 23:59:31.90 DEBUG ==> Setting Magento configuration value 'web/seo/use_rewrites' to '1'
Value was saved.
No modules were changed.
No modules were changed.
Enabled default mode.
magento 23:59:35.88 INFO  ==> Reindexing

**Comment by FraPazGal** [comment] 2024-01-24 16:42
Hello @bastianhilton, I have been able to reproduce the following error using the latest version of our Elasticsearch 8 container:

```
Catalog Search index process error during indexation process:
error=no handler found for uri [/magento2_product_1_v2/document/_mapping?include_type_name=true] and method [PUT]
```

It looks like the Magento container is able to connect to the ElasticSearch one but fails at an installation step related to the search index. This is because we are using the latest ES major. As it is now, Magento 2.4.6 supports both [ES 7.17 and ES 8.5](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html?lang=en). Our Magento container is using ES 7 by default, though we'll need to revisit this when Magento 2.4.7 comes out.

The simple solution is to use ES 7 in your setup, though using ES 8.5 is also an option. In that case you'll need to update the `MAGENTO_SEARCH_ENGINE` environment variable. That said, I have encountered a bug in our container by which we are blocking setting `MAGENTO_SEARCH_ENGINE=elasticsearch8`

https://github.com/bitnami/containers/blob/3b26651f52c2393cf71b5ebb487e1f1950c9d6bc/bitnami/magento/2/debian-11/rootfs/opt/bitnami/scripts/libmagento.sh#L102

I'll create an internal task for the dev team to work on updating that check and reviewing any additional changes necessary. If you want to contribute with a fix feel free to open a PR to update the container, we'll gladly review it and merge it when ready.

**Comment by bastianhilton** [comment] 2024-01-26 21:38
So does that mean downgrade my Elasticsearch install to 7?

**Comment by bastianhilton** [comment] 2024-01-26 23:55
I restarted the bitnami/magento docker installation with Elasticsearch 7.17, now I get this message and can't access the magento pages

[Progress: 1317 / 1331]
Module 'Magento_WeeeGraphQl':
[Progress: 1318 / 1331]
Module 'Magento_CurrencySymbol':
[Progress: 1319 / 1331]
Module 'Magento_Wishlist':
[Progress: 1320 / 1331]
Module 'Magento_WishlistAnalytics':
[Progress: 1321 / 1331]
Module 'Magento_WishlistGraphQl':
[Progress: 1322 / 1331]
Module 'PayPal_Braintree':
[Progress: 1323 / 1331]
Module 'PayPal_BraintreeGraphQl':
[Progress: 1324 / 1331]
Module 'Temando_ShippingRemover':
[Progress: 1325 / 1331]
Enabling caches:
Current status:

1
block_html: 1

full_page: 1
[Progress: 1326 / 1331]
Installing admin user...
[Progress: 1327 / 1331]
Caches clearing:
Cache cleared successfully
[Progress: 1328 / 1331]
Disabling Maintenance Mode:
[Progress: 1329 / 1331]
Post installation file permissions check...
For security, remove write permissions from these directories: '/opt/bitnami/magento/app/etc'
[Progress: 1330 / 1331]
Write installation date...
[Progress: 1331 / 1331]
[SUCCESS]: Magento installation complete.
[SUCCESS]: Magento Admin URI: /admin
Nothing to import.
magento 23:35:38.04 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_frontend' to '0'
Value was saved.
magento 23:35:53.41 DEBUG ==> Setting Magento configuration value 'web/secure/use_in_adminhtml' to '0'
Value was saved.
magento 23:35:57.40 DEBUG ==> Setting Magento configuration value 'web/secure/base_url' to 'https://localhost/'
Value was saved.
magento 23:36:01.39 DEBUG ==> Setting Magento configuration value 'web/unsecure/base_url' to 'http://localhost/'
Value was saved.
magento 23:36:05.29 DEBUG ==> Setting Magento configuration value 'web/seo/use_rewrites' to '1'
Value was saved.
The following modules have been disabled:
- Magento_AdminAdobeImsTwoFactorAuth
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:disable' with the --clear-static-content option to clear them.
The following modules have been disabled:
- Magento_TwoFactorAuth
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:disable' with the --clear-static-content option to clear them.
Enabled default mode.
magento 23:36:37.81 INFO  ==> Reindexing
Design Config Grid index has been rebuilt successfully in 00:00:01
Customer Grid index has been rebuilt successfully in 00:00:02
Category Products index has been rebuilt successfully in 00:00:07
Product Categories index has been rebuilt successfully in 00:00:00
Catalog Rule Product index has been rebuilt successfully in 00:00:03
Product EAV index has been rebuilt successfully in 00:00:03
Stock index has been rebuilt successfully in 00:00:04
Inventory index has been rebuilt successfully in 00:00:01
Catalog Product Rule index has been rebuilt successfully in 00:00:00
Product Price index has been rebuilt successfully in 00:00:06
Catalog Search index has been rebuilt successfully in 00:00:03
magento 23:37:25.12 INFO  ==> Flushing cache
Flushed cache types:
config
layout
block_html
collections
reflection
db_ddl
compiled_config
eav
customer_notification
config_integration
config_integration_api

e
config_webservice

e
magento 23:37:27.01 INFO  ==> Setting PHP expose_php option
magento 23:37:27.02 INFO  ==> Setting PHP output_buffering option
magento 23:37:27.08 INFO  ==> Setting PHP expose_php option
magento 23:37:27.08 INFO  ==> Setting PHP output_buffering option
magento 23:37:27.10 INFO  ==> Persisting Magento installation
magento 23:37:50.70 INFO  ==> ** Magento setup finished! **
magento 23:37:50.71 INFO  ==> ** Starting cron **
magento 23:37:50.72 INFO  ==> ** Starting Apache **
[Fri Jan 26 23:37:50.826941 2024] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.58 (Unix) OpenSSL/1.1.1w configured -- resuming normal operations
[Fri Jan 26 23:37:50.826981 2024] [core:notice] [pid 1] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'

**Comment by FraPazGal** [comment] 2024-01-29 13:40
Hello @bastianhilton, I don't see any error messages in the last logs you shared and the setup using ElasticSearch sueceeded:

```
Catalog Search index has been rebuilt successfully in 00:00:03
```

What error are you getting when accessing the Web UI? If run locally, this is just a matter or opening your browser and opening `localhost:[port_set_in_compose]`

**Comment by bastianhilton** [comment] 2024-01-29 13:48
It wasn't showing anything at all just connection refused. Now I'm using Magento in Softaculous in direct admin because I could never actually get the bitnami image to work

**Comment by FraPazGal** [comment] 2024-01-29 15:01
We are sorry to hear that @bastianhilton. I'll close this ticket now but feel free to open a new one anytime you get back to using any of our products and need help!

**Closed by FraPazGal** 2024-01-29 15:01 UTC
Labels: magento, in-progress, tech-issues
