### ISSUE TITLE
[bitnami/postgresql] Postgres init script no longer works after latest update

### ISSUE THREAD

**Issue by wizardfrag** [bitnami/containers#16933] opened 2022-12-15 12:24 UTC
### Name and Version

bitnami/postgresql:12

### What steps will reproduce the bug?

1. Create a container using a postgres init shell script that contains the following: `psql -d template1 -c "CREATE EXTENSION pg_trgm;"`
2. Note that a password is requested for the user when one wasn't required before

### What is the expected behavior?

```
postgresql 11:54:24.78 INFO  ==> ** Starting PostgreSQL setup **
postgresql 11:54:24.81 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 11:54:24.82 INFO  ==> Loading custom pre-init scripts...
postgresql 11:54:24.83 INFO  ==> Initializing PostgreSQL database...
postgresql 11:54:24.86 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 11:54:24.86 INFO  ==> Generating local authentication configuration
postgresql 11:54:26.10 INFO  ==> Starting PostgreSQL in background...
postgresql 11:54:26.24 INFO  ==> Creating user stonehenge
postgresql 11:54:26.27 INFO  ==> Granting access to "stonehenge" to the database "postgres"
postgresql 11:54:26.30 INFO  ==> Setting ownership for the 'public' schema database "postgres" to "stonehenge"
postgresql 11:54:26.33 INFO  ==> Configuring replication parameters
postgresql 11:54:26.38 INFO  ==> Configuring synchronous_replication
postgresql 11:54:26.38 INFO  ==> Configuring fsync
postgresql 11:54:26.41 INFO  ==> Loading custom scripts...
postgresql 11:54:26.42 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 11:54:26.43 INFO  ==> Starting PostgreSQL in background...
CREATE EXTENSION
postgresql 11:54:26.48 INFO  ==> Enabling remote connections
postgresql 11:54:26.50 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 11:54:26.61 INFO  ==> ** PostgreSQL setup finished! **
```

### What do you see instead?

```
postgresql 11:48:32.46 INFO  ==> ** Starting PostgreSQL setup **
postgresql 11:48:32.48 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 11:48:32.48 INFO  ==> Loading custom pre-init scripts...
postgresql 11:48:32.49 INFO  ==> Initializing PostgreSQL database...
postgresql 11:48:32.51 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 11:48:32.51 INFO  ==> Generating local authentication configuration
postgresql 11:48:33.41 INFO  ==> Starting PostgreSQL in background...
postgresql 11:48:33.54 INFO  ==> Creating user stonehenge
postgresql 11:48:33.56 INFO  ==> Granting access to "stonehenge" to the database "postgres"
postgresql 11:48:33.59 INFO  ==> Setting ownership for the 'public' schema database "postgres" to "stonehenge"
postgresql 11:48:33.62 INFO  ==> Configuring replication parameters
postgresql 11:48:33.65 INFO  ==> Configuring synchronous_replication
postgresql 11:48:33.66 INFO  ==> Configuring fsync
postgresql 11:48:33.68 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
postgresql 11:48:33.79 INFO  ==> Loading custom scripts...
postgresql 11:48:33.80 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
postgresql 11:48:33.80 INFO  ==> Starting PostgreSQL in background...
Password for user postgres: 
psql: error: fe_sendauth: no password supplied
postgresql 11:48:33.93 INFO  ==> Stopping PostgreSQL...
waiting for server to shut down.... done
server stopped
```

**Comment by wizardfrag** [comment] 2022-12-15 12:29
This seems to be related to the following piece of code:

https://github.com/bitnami/containers/blob/5e9a6786c603da4cf5ff6badf848b2a61e5a4119/bitnami/postgresql/12/debian-11/rootfs/opt/bitnami/scripts/libpostgresql.sh#L657-L658

**Comment by irizzant** [comment] 2022-12-16 13:24
I'm hitting the same issue on version 14, my initdb script executing a pg_restore is now requesting a password even with the POSTGRESQL_PASSWORD set and it didn't before

**Comment by migruiz4** [comment] 2022-12-19 14:55
Hi @wizardfrag, @irizzant,

The `postgresql_stop` was added as part of the fix for this issue: https://github.com/bitnami/charts/issues/12983#issuecomment-1352710420

My colleague @rafariossaa added it after detecting initialization settings were not taking effect during the custom init scripts execution because PostgreSQL wasn't being restarted.

I would say that commands requesting passwords during init scripts is not a bug but the originally intended behavior, and instead, the previous behavior of not requesting a password was also caused by the same bug.

Please make sure your scripts are also including the username and password in the executions. I hope the following example helps you.

Using the below docker-compose:
```
version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:12
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
      - /sample_path_to/test.sh:/docker-entrypoint-initdb.d/test.sh
    environment:
      - 'ALLOW_EMPTY_PASSWORD=no'
      - 'POSTGRESQL_PASSWORD=secretpass'

volumes:
  postgresql_data:
    driver: local
```

The content of the init script should be:
```
PGPASSWORD="${POSTGRESQL_PASSWORD}" psql -U "${POSTGRESQL_USERNAME}" -d template1 -c "CREATE EXTENSION pg_trgm;"
```

The same would apply for `pg_restore`:
```
PGPASSWORD="${POSTGRESQL_PASSWORD}" pg_restore -U "${POSTGRESQL_USERNAME}" ...
```

**Comment by richban** [comment] 2022-12-20 16:56
I have a similar issue after upgrading from `bitnami/postgresql:13.7.0` to `bitnami/postgresql:14`:

`docker-compose.yaml`

```yaml
database:
  image: 'bitnami/postgresql:14'
  environment:
    - POSTGRESQL_USERNAME=my_user
    - POSTGRESQL_PASSWORD=password
    - POSTGRESQL_DATABASE=my_db
    - POSTGRESQL_INITSCRIPTS_USERNAME=postgres
    - POSTGRESQL_INITSCRIPTS_PASSWORD=password
  volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  ports:
    - "5432"
```

`docker-entrypoint-initdb.d/postgis.sql`:

```sql
ALTER USER my_user WITH SUPERUSER;
CREATE EXTENSION postgis;
```

output:

```
2022-12-20 17:43:35 postgresql 16:43:35.53 
2022-12-20 17:43:35 postgresql 16:43:35.56 Welcome to the Bitnami postgresql container
2022-12-20 17:43:35 postgresql 16:43:35.58 Subscribe to project updates by watching https://github.com/bitnami/containers
2022-12-20 17:43:35 postgresql 16:43:35.61 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2022-12-20 17:43:35 postgresql 16:43:35.63 
2022-12-20 17:43:35 postgresql 16:43:35.81 INFO  ==> ** Starting PostgreSQL setup **
2022-12-20 17:43:35 postgresql 16:43:35.96 INFO  ==> Validating settings in POSTGRESQL_* env vars..
2022-12-20 17:43:36 postgresql 16:43:36.04 INFO  ==> Loading custom pre-init scripts...
2022-12-20 17:43:36 postgresql 16:43:36.10 INFO  ==> Initializing PostgreSQL database...
2022-12-20 17:43:36 postgresql 16:43:36.36 INFO  ==> pg_hba.conf file not detected. Generating it...
2022-12-20 17:43:36 postgresql 16:43:36.39 INFO  ==> Generating local authentication configuration
2022-12-20 17:43:36 postgresql 16:43:36.56 INFO  ==> Deploying PostgreSQL with persisted data...
2022-12-20 17:43:36 postgresql 16:43:36.67 INFO  ==> Configuring replication parameters
2022-12-20 17:43:37 postgresql 16:43:37.06 INFO  ==> Configuring fsync
2022-12-20 17:43:37 postgresql 16:43:37.18 INFO  ==> Configuring synchronous_replication
2022-12-20 17:43:37 postgresql 16:43:37.38 INFO  ==> Loading custom scripts...
2022-12-20 17:43:37 postgresql 16:43:37.44 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
2022-12-20 17:43:37 postgresql 16:43:37.47 INFO  ==> Starting PostgreSQL in background...
2022-12-20 17:43:38 postgresql 16:43:38.01 INFO  ==> Stopping PostgreSQL...
2022-12-20 17:43:38 waiting for server to shut down.... done
2022-12-20 17:43:38 server stopped
```

Behaviour on `bitnami/postgresql:13.7.0`:

```bash
2022-12-20 17:52:56 postgresql 16:52:56.17 
2022-12-20 17:52:56 postgresql 16:52:56.20 Welcome to the Bitnami postgresql container
2022-12-20 17:52:56 postgresql 16:52:56.22 Subscribe to project updates by watching https://github.com/bitnami/containers
2022-12-20 17:52:56 postgresql 16:52:56.25 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2022-12-20 17:52:56 postgresql 16:52:56.27 
2022-12-20 17:52:56 postgresql 16:52:56.45 INFO  ==> ** Starting PostgreSQL setup **
2022-12-20 17:52:56 postgresql 16:52:56.60 INFO  ==> Validating settings in POSTGRESQL_* env vars..
2022-12-20 17:52:56 postgresql 16:52:56.68 INFO  ==> Loading custom pre-init scripts...
2022-12-20 17:52:56 postgresql 16:52:56.75 INFO  ==> Initializing PostgreSQL database...
2022-12-20 17:52:57 postgresql 16:52:57.02 INFO  ==> pg_hba.conf file not detected. Generating it...
2022-12-20 17:52:57 postgresql 16:52:57.04 INFO  ==> Generating local authentication configuration
2022-12-20 17:53:00 postgresql 16:53:00.36 INFO  ==> Starting PostgreSQL in background...
2022-12-20 17:53:00 postgresql 16:53:00.89 INFO  ==> Creating user my_user
2022-12-20 17:53:00 postgresql 16:53:00.99 INFO  ==> Granting access to "my_user" to the database "my_db"
2022-12-20 17:53:01 postgresql 16:53:01.18 INFO  ==> Setting ownership for the 'public' schema database "my_db" to "planetrics"
2022-12-20 17:53:02 postgresql 16:53:02.17 INFO  ==> Loading custom scripts...
2022-12-20 17:53:02 postgresql 16:53:02.23 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
2022-12-20 17:53:02 postgresql 16:53:02.25 INFO  ==> Starting PostgreSQL in background...
2022-12-20 17:53:02 postgresql 16:53:02.42 INFO  ==> Enabling remote connections
2022-12-20 17:53:02 postgresql 16:53:02.52 INFO  ==> Stopping PostgreSQL...
2022-12-20 17:53:02 waiting for server to shut down.... done
2022-12-20 17:53:02 server stopped
2022-12-20 17:53:02 
2022-12-20 17:53:02 postgresql 16:53:02.72 INFO  ==> ** PostgreSQL setup finished! **
2022-12-20 17:53:02 postgresql 16:53:02.90 INFO  ==> ** Starting PostgreSQL **
2022-12-20 17:53:02 2022-12-20 16:53:02.994 GMT [1] LOG:  pgaudit extension initialized
2022-12-20 17:53:03 2022-12-20 16:53:03.033 GMT [1] LOG:  starting PostgreSQL 13.7 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2022-12-20 17:53:03 2022-12-20 16:53:03.041 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-12-20 17:53:03 2022-12-20 16:53:03.041 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2022-12-20 17:53:03 2022-12-20 16:53:03.044 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2022-12-20 17:53:03 2022-12-20 16:53:03.063 GMT [433] LOG:  database system was shut down at 2022-12-20 16:53:02 GMT
2022-12-20 17:53:03 2022-12-20 16:53:03.080 GMT [1] LOG:  database system is ready to accept connections
```

**Comment by irizzant** [comment] 2022-12-21 07:41
Thanks for the update @migruiz4 I see that adding `PGPASSWORD="${POSTGRESQL_PASSWORD}"` makes the `pg_restore` working again

**Comment by migruiz4** [comment] 2022-12-21 16:28
Thanks for the feedback @irizzant, I'm glad my suggestion fixed the issue!

@richban, in this case it may be caused by a permissions issue. The `*.sql` scripts are executed with the credentials `POSTGRESQL_INITSCRIPTS_USERNAME` and `POSTGRESQL_INITSCRIPTS_PASSWORD`, which default to `POSTGRESQL_USERNAME` and `POSTGRESQL_PASSWORD` respectively.

In this case, the user `my_user` may not have the necessary privileges to make a superuser himself.

In that case, you may need to change the initscripts username and password to `postgres` and `$POSTGRESQL_POSTGRES_PASSWORD` so the initscript is executed with higher privileges.

**Comment by richban** [comment] 2022-12-22 12:31
> Thanks for the feedback @irizzant, I'm glad my suggestion fixed the issue!
> 
> @richban, in this case it may be caused by a permissions issue. The `*.sql` scripts are executed with the credentials `POSTGRESQL_INITSCRIPTS_USERNAME` and `POSTGRESQL_INITSCRIPTS_PASSWORD`, which default to `POSTGRESQL_USERNAME` and `POSTGRESQL_PASSWORD` respectively.
> 
> The root cause of your issue may be that the user `my_user` does not have the necessary privileges to make a superuser himself.
> 
> In that case, you may need to change the initscripts username and password to `postgres` and `$POSTGRESQL_POSTGRES_PASSWORD` so the initscript is executed with higher privileges.

@migruiz4 thank you for your comment!

I am not sure if I follow. My assumption is `POSTGRESQL_INITSCRIPTS_USERNAME` is defined, thus `postgres` user has the right privileges to create the extension and alter `my_user` permissions.

Regardless that, the above init script is working for `bitnami/postgres:13.7.0` thus there has to be some change for version `14.0` which is breaking. Also I have managed to obtain an older image of ``bitnami/postgres:14` where the above mentioned init script works.

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/6967088/209134799-d8bff0a5-b212-46b5-ac45-96d23e27e93e.png">

**Comment by migruiz4** [comment] 2023-01-03 11:14
Hi @richban, I'm sorry for the late response.

I'm sorry if my previous answer wasn't very clear. I will try to sum up the events that caused this issue.

> The postgresql_stop was added as part of the fix for this issue: https://github.com/bitnami/charts/issues/12983#issuecomment-1352710420
>
> My colleague @rafariossaa added it after detecting initialization settings were not taking effect during the custom init scripts execution because PostgreSQL wasn't being restarted.

Prior versions of the Postgresql issue were affected by a bug where users' authentication and authorization weren't yet applied by the time init scripts were executed.

This caused, for example, commands like the one OP shared that previously worked, to now fail unless authentication settings are provided (`PG_PASSWORD` and `-u` flag).

The case OP shared was with `*.sh` init scripts.
In most cases, `*.sql` init scripts should not be affected as they are executed with the credentials `$POSTGRESQL_INITSCRIPTS_USERNAME:$POSTGRESQL_INITSCRIPTS_PASSWORD`, so no additional authentication settings are required.

-----

Now getting to your case, your script is an exception, because you are including a **privileged** command (`ALTER USER my_user WITH SUPERUSER;`).
Your init script worked in previous versions because any user could run any command. Now that auth is applied by the time init scripts are executed, only privileged users can run privileged commands.

By default, `$POSTGRESQL_INITSCRIPTS_USERNAME=$POSTGRESQL_USERNAME`, and as in your case `$POSTGRESQL_USERNAME=my_user`, your init scripts are being executed as `my_user`. Meaning that your user is trying to set himself as SUPERUSER, which will fail as your user is not yet SUPERUSER.

To solve your issue, you will need to additionally override the env variables `$POSTGRESQL_INITSCRIPTS_USERNAME`/`$POSTGRESQL_INITSCRIPTS_PASSWORD` to user `postgres` and its password, as `postgres` is the only user that has the necessary privileges to run your command (`ALTER USER my_user WITH SUPERUSER;`).

**Comment by richban** [comment] 2023-01-20 17:12
@migruiz4 thank you for your exhaustive explanation - solved the issue as you described.

**Comment by migruiz4** [comment] 2023-01-23 09:01
Thank you for your feedback @richban!

I will close this issue as I think the root cause of this behavior is clear now.

**Closed by migruiz4** 2023-01-23 09:01 UTC
Labels: in-progress, tech-issues, postgresql
