### ISSUE TITLE
How does postgres repmagr implement witness service? thank you

### ISSUE THREAD

**Issue by zhbog521** [bitnami/containers#15975] opened 2022-12-05 07:48 UTC
### Name and Version

bitnami/postgresql-repmgr

### What is the problem this feature will solve?

How does postgres repmagr implement witness service? thank you

### What is the feature you are proposing to solve the problem?

How does postgres repmagr implement witness service? thank you

**Comment by javsalgar** [comment] 2022-12-05 08:46
Duplicate of https://github.com/bitnami/containers/issues/15976

**Closed by javsalgar** 2022-12-05 08:46 UTC
Labels: triage, feature-request
