### ISSUE TITLE
[bitnami/cassandra] cqlsh returns - [Bad credentials] message="Provided username cassandra and/or password are incorrect"

### ISSUE THREAD

**Issue by remusbaciu** [bitnami/containers#14627] opened 2022-11-23 11:00 UTC
### Name and Version

docker.io/bitnami/cassandra:4.0.7-debian-11-r9

### What steps will reproduce the bug?

environment
mac os/ubuntu -> kind local k8s cluster

```
helm install cassandra bitnami/cassandra --set dbUser.user cassandra --set dbUser.password password
```
wait for pod to be ready
running cqlsh from local pod or via port forwarding returns the following error

```
 k exec -it pod/cassandra-0 bash
+ kubectl exec -it pod/cassandra-0 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@cassandra-0:/$ cqlsh -u cassandra -p password
Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Failed to authenticate to 127.0.0.1:9042: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"')})`
```
### What is the expected behavior?

enter cqlsh

### What do you see instead?

```
 k exec -it pod/cassandra-0 bash
+ kubectl exec -it pod/cassandra-0 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@cassandra-0:/$ cqlsh -u cassandra -p password
Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Failed to authenticate to 127.0.0.1:9042: Error from server: code=0100 [Bad credentials] message="Provided username cassandra and/or password are incorrect"')})
```

**Comment by aoterolorenzo** [comment] 2022-11-28 10:07
Hi @remusbaciu,

Thank you for reporting the issue. I see that you are using the bitnami's cassandra chart, so I'm afraid the place to submit the issue is in the [bitnami's charts repository](https://github.com/bitnami/charts). Could you re-submit it there? 

I'm closing this one meanwhile.

**Closed by aoterolorenzo** 2022-11-28 10:07 UTC
Labels: in-progress, tech-issues, cassandra
