### ISSUE TITLE
[bitnami/postgresql] Tag 14 is broken in docker hub

### ISSUE THREAD

**Issue by jmueller42** [bitnami/containers#2689] opened 2022-08-10 12:19 UTC
### Name and Version

bitnami/postgresql:14

### What steps will reproduce the bug?

1. Create Dockerfile:
```
FROM bitnami/postgresql:14
RUN ls
```

2. Execute image build
```
docker run -v $PWD:/workspace --entrypoint=/kaniko/executor gcr.io/kaniko-project/executor:v1.8.1-debug --verbosity=info --context . --dockerfile Dockerfile --no-push
```

### What is the expected behavior?

to be able to use bitnami/postgresql:14 as base image

### What do you see instead?

INFO[0000] Retrieving image manifest bitnami/postgresql:14 
INFO[0000] Retrieving image bitnami/postgresql:14 from registry index.docker.io 
error building image: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377

### Additional information

The last successful build using bitnami/postgresql:14 as base image was on august 8. 11am utc+0.

bitnami/postgresql:13 and bitnami/postgresql:12 are still working.

**Comment by BernhardGruen** [comment] 2022-08-10 12:21
I am affected by this issue too.

**Comment by gongomgra** [comment] 2022-08-16 10:00
Hi @jmueller42, @BernhardGruen 

I see in our [GitHub repository for PostgreSQL](https://github.com/bitnami/containers/tree/main/bitnami/postgresql) that branch 14 is the only one without a recent update (like the rest of branches). We will work on releasing a new revision of the container. Let's see if the new version solves your issue somehow.

**Comment by BernhardGruen** [comment] 2022-08-16 12:43
Hey @gongomgra,

Thank you for your answer. It seems the problem is not present anymore with the newly released container version.

**Comment by gongomgra** [comment] 2022-08-16 14:04
Hi @BernhardGruen ,

Good to know it solved your issue! Please @jmueller42 confirm if it worked for you as well

**Comment by jmueller42** [comment] 2022-08-16 14:24
I can confirm it's fixed for me too.
Thank you very much @gongomgra

**Comment by gongomgra** [comment] 2022-08-16 14:27
Hi @jmueller42, good to know. We are closing this ticket now!

**Closed by gongomgra** 2022-08-16 14:27 UTC
Labels: in-progress, tech-issues, postgresql
