### ISSUE TITLE
[bitnami/pgbouncer] Can't run PgBouncer app in Docker

### ISSUE THREAD

**Issue by Ilya-lab** [bitnami/containers#4235] opened 2022-08-25 00:40 UTC
### Name and Version

bitnami/pgbouncer-1.17.0

### What steps will reproduce the bug?

Can't run PgBouncer app in Docker. If I go into the container, I can't access the folders. Also there is no user in the container.
Errors:
```
pgbouncer 08:10:30.65 Welcome to the Bitnami pgbouncer container
pgbouncer 08:10:30.66 Subscribe to project updates by watching https://github.com/bitnami/containers
pgbouncer 08:10:30.66 Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgbouncer 08:10:30.67
pgbouncer 08:10:30.71 INFO ==> ** Starting PgBouncer setup **
pgbouncer 08:10:30.73 INFO ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 08:10:30.89 INFO ==> Initializing PgBouncer...
ls: cannot access '/bitnami/pgbouncer/conf': Operation not permitted
pgbouncer 08:10:30.96 INFO ==> Waiting for PostgreSQL backend to be accessible
pgbouncer 08:10:31.00 INFO ==> Backend 192.168.ZZZ.ZZZ:5435 accessible
pgbouncer 08:10:31.00 INFO ==> Configuring credentials
pgbouncer 08:10:31.01 INFO ==> Creating configuration file
pgbouncer 08:10:31.31 INFO ==> Loading custom scripts...

pgbouncer 08:10:31.33 INFO ==> ** PgBouncer setup finished! **
pgbouncer 08:10:31.36 INFO ==> ** Starting PgBouncer **
2022-08-24 08:10:31.498 UTC [1] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 152
2022-08-24 08:10:31.500 UTC [1] LOG listening on 0.0.0.0:6432
2022-08-24 08:10:31.500 UTC [1] LOG listening on unix:/tmp/.s.PGSQL.6432
2022-08-24 08:10:31.500 UTC [1] LOG process up: PgBouncer 1.17.0, libevent 2.1.12-stable (epoll), adns: c-ares 1.17.1, tls: OpenSSL 1.1.1n 15 Mar 2022
```
When I tryied to connect with psql I get error:
```
2022-08-24 08:36:11.840 UTC [1] LOG C-0x7f9fe6570bc0: (nodb)/(nouser)@172.17.0.1:60388 no such user: uaser
2022-08-24 08:36:11.840 UTC [1] LOG C-0x7f9fe6570bc0: (nodb)/uaser@172.17.0.1:60388 login attempt: db=base user=uaser tls=no
pgbouncer: Cannot get system entropy
```

### What do you see instead?

I thinks that pgbouncer cannot load .ini file and users.txt
ls: `cannot access '/bitnami/pgbouncer/conf': Operation not permitted`
an 1001 user, and other rights get on this directory

**Comment by fmulero** [comment] 2022-08-25 06:58
Hi @Ilya-lab, thanks for using bitnami images

Could you share a `docker-compose.yaml` file or instructions about how you are mounting the volumes? The container runs by default with the user 1001 and it needs read access to any mounted volume.

PD: Please use [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to apply a readable format in your comments, mainly if you are pasting code, console output or logs

**Comment by Ilya-lab** [comment] 2022-08-25 07:49
I haven't any 1001 user in /etc/passwd file as inside container or outside it. I'm not using docker-compose, starting docker container at command line:
`docker run --name my_pgbouncer -e POSTGRESQL_PASSWORD="12345" -e POSTGRESQL_HOST="192.168.XXX.YYY" -e POSTGRESQL_PORT="5432" -p 6432:6432 -v /outside_dir/pgbouncer/conf/:/opt/bitnami/pgbouncer/conf/ imidge_pgbouncer`
I tryed start container with root user, but no changes. If I enter to container, I can't list directories too.

**Comment by fmulero** [comment] 2022-08-26 06:53
Have you taken a look to [README file](https://github.com/bitnami/containers/tree/main/bitnami/pgbouncer) for pgbouncer? [Here](https://github.com/bitnami/containers/tree/main/bitnami/pgbouncer#configuration-file) you can find how to mount configuration files.

About the user 1001, it comes from [here](https://github.com/bitnami/containers/blob/f69988ecdbaaa258721a3d37bc05f3248bfceeec/bitnami/pgbouncer/1/debian-11/Dockerfile#L45). Also you can find more information about our non-root containers in the following links, including the problematic with the mounted volumes:
* https://docs.bitnami.com/tutorials/work-with-non-root-containers
* https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift

**Comment by Ilya-lab** [comment] 2022-08-26 07:38
I'm use it:
[root@CServer2 ~]# docker run --user root --name my_pgbouncer -e POSTGRESQL_PASSWORD="****" -e POSTGRESQL_HOST="192.168.XXX.YYY" -e POSTGRESQL_PORT="5435" -p 6432:6432 -v /mylocation/pgbouncer/conf/:/opt/bitnami/pgbouncer/conf/ bitnami/pgbouncer
pgbouncer 07:31:49.85 
pgbouncer 07:31:49.85 Welcome to the Bitnami pgbouncer container
pgbouncer 07:31:49.85 Subscribe to project updates by watching https://github.com/bitnami/containers
pgbouncer 07:31:49.85 Submit issues and feature requests at https://github.com/bitnami/containers/issues
pgbouncer 07:31:49.85 
pgbouncer 07:31:49.86 INFO  ==> ** Starting PgBouncer setup **
pgbouncer 07:31:49.87 INFO  ==> Validating settings in PGBOUNCER_* env vars...
pgbouncer 07:31:50.15 INFO  ==> Initializing PgBouncer...
ls: cannot access '/bitnami/pgbouncer/conf': Operation not permitted
pgbouncer 07:31:50.18 INFO  ==> Waiting for PostgreSQL backend to be accessible
pgbouncer 07:31:50.19 INFO  ==> Backend 192.168.XXX.XXX:5435 accessible
pgbouncer 07:31:50.19 INFO  ==> Configuring credentials
pgbouncer 07:31:50.19 INFO  ==> Creating configuration file
pgbouncer 07:31:50.82 INFO  ==> Loading custom scripts...

pgbouncer 07:31:50.82 INFO  ==> ** PgBouncer setup finished! **
pgbouncer 07:31:50.84 INFO  ==> ** Starting PgBouncer **
2022-08-26 07:31:50.860 UTC [1] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 152
2022-08-26 07:31:50.861 UTC [1] LOG listening on 0.0.0.0:6432
2022-08-26 07:31:50.861 UTC [1] LOG listening on unix:/tmp/.s.PGSQL.6432
2022-08-26 07:31:50.861 UTC [1] LOG process up: PgBouncer 1.17.0, libevent 2.1.12-stable (epoll), adns: c-ares 1.17.1, tls: OpenSSL 1.1.1n  15 Mar 2022
2022-08-26 07:32:50.868 UTC [1] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
2022-08-26 07:32:57.438 UTC [1] LOG C-0x7fec560b5bc0: (nodb)/postgres@172.17.0.1:41208 login attempt: db=postgres user=postgres tls=no
pgbouncer: Cannot get system entropy

But if I start connect to database
`psql -h localhost -p 6432 -U postgres postgres`
I have ERROR 
`Cannot get system entropy`

**Comment by fmulero** [comment] 2022-08-26 08:47
Could you have a look to this [issue](https://github.com/bitnami/bitnami-docker-pgbouncer/issues/35) ?

**Comment by Ilya-lab** [comment] 2022-08-26 09:47
Yes, but problem not solved. Or I don't understand how to do it.

**Comment by fmulero** [comment] 2022-08-29 09:24
I've just seen you are also facing the same issue with [other container](https://github.com/edoburu/docker-pgbouncer/issues/66) Could your issue be related to a custom configuration, or a recent boot of the instance running docker? There are a lot of documentation about "Not enough entropy" on docker containers and I think it is not related to the bitnami container itself

**Comment by dforste** [comment] 2022-08-30 13:08
I just ran into this issue as well. It seems it is a problem with the base image in some way. We can run `ls` in a current directory but when passing it a path it fails and thus the scripts fail as well. 
To reproduce: 
```
export tmp=$(mktemp -d)
touch $tmp/test
chown -R 1001 $tmp
docker run --rm -it -v $tmp:/bitnami/pgbouncer/conf docker.io/bitnami/pgbouncer:1.17.0-debian-11-r18 bash
# pgbouncer 13:04:01.27
# pgbouncer 13:04:01.27 Welcome to the Bitnami pgbouncer container
# pgbouncer 13:04:01.27 Subscribe to project updates by watching https://github.com/bitnami/containers
# pgbouncer 13:04:01.28 Submit issues and feature requests at https://github.com/bitnami/containers/issues
# pgbouncer 13:04:01.28
ls -A /bitnami/pgbouncer/conf
# ls: cannot access '/bitnami/pgbouncer/conf': Operation not permitted
```

**Comment by dforste** [comment] 2022-08-30 13:17
I have opened an upstream issue https://github.com/bitnami/minideb/issues/134 to help address if they can.

**Comment by dforste** [comment] 2022-08-30 18:09
Turns out the docker version is too old to work these days. Upgrading docker-ce fixed this issue.

**Comment by Ilya-lab** [comment] 2022-08-31 08:34
Yes it really is

**Comment by fmulero** [comment] 2022-08-31 08:59
Thanks for sharing it. I will close the issue

**Closed by fmulero** 2022-08-31 08:59 UTC
Labels: tech-issues, triage, pgbouncer
