### ISSUE TITLE
pgbouncer - Mangled userlist file

### ISSUE THREAD

**Issue by SteveBurgessStantec** [bitnami/containers#48959] opened 2023-09-18 08:53 UTC
### Name and Version

bitnami/pgbouncer:1.20.1-debian-11-r33

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Running the bitnami/pgbouncer image with `POSTGRESQL_USERNAME` and `POSTGRESQL_PASSWORD` env's set results in a mangled userlist.txt file.

### What is the expected behavior?

The user list file should contain the username and password being passed via the env's and should look something like this

"USERNAME" "PASSWORD"

### What do you see instead?

Instead, I'm now seeing this
```
pgbouncer_escape_auth USERNAME pgbouncer_escape_auth PASSWORD
```
### Additional information

I'm assuming it was this commit that happened a few days ago that is causing the issue.

https://github.com/bitnami/containers/blame/6b55d2ac02f3ca88d74b12b5587156172b794351/bitnami/pgbouncer/1/debian-11/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L206

**Comment by hbusul** [comment] 2023-09-18 09:49
This issue popped out for us as well in development. We also make use of "PGBOUNCER_USERLIST" env var in addition to "POSTGRESQL_USERNAME" and "POSTGRESQL_PASSWORD"

**Comment by jotamartos** [comment] 2023-09-25 07:37
Closing this as the issue is now resolved 

https://github.com/bitnami/containers/issues/48264#issuecomment-1732229367

**Closed by jotamartos** 2023-09-25 07:37 UTC
Labels: in-progress, tech-issues, pgbouncer
