### ISSUE TITLE
mongodb mistakenly replica set config

### ISSUE THREAD

**Issue by NormanTrinh** [bitnami/containers#53703] opened 2023-12-10 10:38 UTC
### Name and Version

bitnami/mongodb:5.0.23

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I'm using docker compose, these are the setups:
```yaml
  mongodb-primary:
    image: docker.io/bitnami/mongodb:5.0.23
    container_name: mongo1
    user: root
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=password123

      # set replica
      - MONGODB_ADVERTISED_HOSTNAME=mongo1
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=abcdefghijklmno

    volumes:
      - './app_data/mongo_master_data:/bitnami/mongodb'

  mongodb-secondary1:
    image: docker.io/bitnami/mongodb:5.0.23
    container_name: mongo2
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo2
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=abcdefghijklmno

  mongodb-secondary2:
    image: docker.io/bitnami/mongodb:5.0.23
    container_name: mongo3
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_ADVERTISED_HOSTNAME=mongo3
      - MONGODB_INITIAL_PRIMARY_HOST=mongo1
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=abcdefghijklmno
```

### What is the expected behavior?

When i access to mongo1 with the following command:
```
mongosh --host mongo1:27017 -u root -p password123 admin

rs.status();
```
I want it show the log like this (I want the output is `syncSourceHost: 'mongo1:27017'` in all SECONDARY nodes):
```
rs0 [direct: primary] test> rs.status()
{
  set: 'rs0',
  date: ISODate('2023-12-10T10:24:10.701Z'),
  myState: 1,
  term: Long('2'),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long('2000'),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastCommittedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    appliedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    durableOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z')
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1702203815, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'electionTimeout',
    lastElectionDate: ISODate('2023-12-10T10:20:45.542Z'),
    electionTerm: Long('2'),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 0, i: 0 }), t: Long('-1') },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1702203641, i: 15 }), t: Long('1') },
    numVotesNeeded: 1,
    priorityAtElection: 5,
    electionTimeoutMillis: Long('10000'),
    newTermStartDate: ISODate('2023-12-10T10:20:45.547Z'),
    wMajorityWriteAvailabilityDate: ISODate('2023-12-10T10:20:45.554Z')
  },
  members: [
    {
      _id: 0,
      name: 'mongo1:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 206,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1702203645, i: 1 }),
      electionDate: ISODate('2023-12-10T10:20:45.000Z'),
      configVersion: 6,
      configTerm: 2,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'mongo2:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 135,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.226Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.222Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo1:27017',
      syncSourceId: 2,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    },
    {
      _id: 2,
      name: 'mongo3:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 163,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.229Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.134Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo1:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1702203845, i: 1 }),
    signature: {
      hash: Binary.createFromBase64('xUdtHhUsMFjQ/Sy/VWjKogFQ29A=', 0),
      keyId: Long('7310908969227124742')
    }
  },
  operationTime: Timestamp({ t: 1702203845, i: 1 })
}
```

### What do you see instead?
You can see in SECONDARY node, mongo2 will sync from mongo3, mongo3 will sync from mongo1 if i'm using the setup above!!!
```
rs0 [direct: primary] test> rs.status()
{
  set: 'rs0',
  date: ISODate('2023-12-10T10:24:10.701Z'),
  myState: 1,
  term: Long('2'),
  syncSourceHost: '',
  syncSourceId: -1,
  heartbeatIntervalMillis: Long('2000'),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastCommittedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    appliedOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    durableOpTime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
    lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
    lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z')
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1702203815, i: 1 }),
  electionCandidateMetrics: {
    lastElectionReason: 'electionTimeout',
    lastElectionDate: ISODate('2023-12-10T10:20:45.542Z'),
    electionTerm: Long('2'),
    lastCommittedOpTimeAtElection: { ts: Timestamp({ t: 0, i: 0 }), t: Long('-1') },
    lastSeenOpTimeAtElection: { ts: Timestamp({ t: 1702203641, i: 15 }), t: Long('1') },
    numVotesNeeded: 1,
    priorityAtElection: 5,
    electionTimeoutMillis: Long('10000'),
    newTermStartDate: ISODate('2023-12-10T10:20:45.547Z'),
    wMajorityWriteAvailabilityDate: ISODate('2023-12-10T10:20:45.554Z')
  },
  members: [
    {
      _id: 0,
      name: 'mongo1:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 206,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1702203645, i: 1 }),
      electionDate: ISODate('2023-12-10T10:20:45.000Z'),
      configVersion: 6,
      configTerm: 2,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: 'mongo2:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 135,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.226Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.222Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo3:27017',
      syncSourceId: 2,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    },
    {
      _id: 2,
      name: 'mongo3:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 163,
      optime: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDurable: { ts: Timestamp({ t: 1702203845, i: 1 }), t: Long('2') },
      optimeDate: ISODate('2023-12-10T10:24:05.000Z'),
      optimeDurableDate: ISODate('2023-12-10T10:24:05.000Z'),
      lastAppliedWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastDurableWallTime: ISODate('2023-12-10T10:24:05.552Z'),
      lastHeartbeat: ISODate('2023-12-10T10:24:09.229Z'),
      lastHeartbeatRecv: ISODate('2023-12-10T10:24:10.134Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: 'mongo1:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 6,
      configTerm: 2
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1702203845, i: 1 }),
    signature: {
      hash: Binary.createFromBase64('xUdtHhUsMFjQ/Sy/VWjKogFQ29A=', 0),
      keyId: Long('7310908969227124742')
    }
  },
  operationTime: Timestamp({ t: 1702203845, i: 1 })
}
```

**Comment by NormanTrinh** [comment] 2023-12-10 18:14
I have another question, if I stop mongo1 or mongo2 or mongo3, the log still reports `Heartbeat failed after max retries`, does not automatically vote for new primary, what should I do, thank you.

**Comment by fmulero** [comment] 2023-12-20 10:09
Hi @NormanTrinh, thanks for using Bitnami containers.

Please, for doubts about how MongoDB works please refer to the official [MongoDB channels](https://www.mongodb.com/support) and [MongoDB documentation](https://www.mongodb.com/docs/v5.0/replication/). 

About your initial doubt, please have a look to the [MongoDB chaining configuration](https://www.mongodb.com/docs/manual/reference/replica-configuration/#mongodb-rsconf-rsconf.settings.chainingAllowed). That feature is enabled by default and allows secondary members replicate data from other secondary members.

About your second, I couldn't reproduce your issue. In my case after stopping `mongo1` I could see how `mongo3` become primary node:
```json
{
  set: 'rs0',
  date: ISODate('2023-12-20T10:00:19.877Z'),
  myState: 2,
  term: Long('3'),
  syncSourceHost: 'mongo3:27017',
  syncSourceId: 1,
  heartbeatIntervalMillis: Long('2000'),
  majorityVoteCount: 2,
  writeMajorityCount: 2,
  votingMembersCount: 3,
  writableVotingMembersCount: 3,
  optimes: {
    lastCommittedOpTime: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
    lastCommittedWallTime: ISODate('2023-12-20T10:00:17.854Z'),
    readConcernMajorityOpTime: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
    appliedOpTime: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
    durableOpTime: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
    lastAppliedWallTime: ISODate('2023-12-20T10:00:17.854Z'),
    lastDurableWallTime: ISODate('2023-12-20T10:00:17.854Z')
  },
  lastStableRecoveryTimestamp: Timestamp({ t: 1703066359, i: 2 }),
  electionParticipantMetrics: {
    votedForCandidate: true,
    electionTerm: Long('3'),
    lastVoteDate: ISODate('2023-12-20T09:54:47.828Z'),
    electionCandidateMemberId: 1,
    voteReason: '',
    lastAppliedOpTimeAtElection: { ts: Timestamp({ t: 1703066087, i: 1 }), t: Long('2') },
    maxAppliedOpTimeInSet: { ts: Timestamp({ t: 1703066087, i: 1 }), t: Long('2') },
    priorityAtElection: 1,
    newTermStartDate: ISODate('2023-12-20T09:54:47.841Z'),
    newTermAppliedDate: ISODate('2023-12-20T09:54:47.843Z')
  },
  members: [
    {
      _id: 0,
      name: 'mongo1:27017',
      health: 0,
      state: 8,
      stateStr: '(not reachable/healthy)',
      uptime: 0,
      optime: { ts: Timestamp({ t: 0, i: 0 }), t: Long('-1') },
      optimeDurable: { ts: Timestamp({ t: 0, i: 0 }), t: Long('-1') },
      optimeDate: ISODate('1970-01-01T00:00:00.000Z'),
      optimeDurableDate: ISODate('1970-01-01T00:00:00.000Z'),
      lastAppliedWallTime: ISODate('2023-12-20T09:54:47.841Z'),
      lastDurableWallTime: ISODate('2023-12-20T09:54:47.841Z'),
      lastHeartbeat: ISODate('2023-12-20T10:00:18.621Z'),
      lastHeartbeatRecv: ISODate('2023-12-20T09:54:56.847Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: 'Error connecting to mongo1:27017 :: caused by :: Could not find address for mongo1:27017: SocketException: Host not found (authoritative)',
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      configVersion: 8,
      configTerm: 3
    },
    {
      _id: 1,
      name: 'mongo3:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 1559,
      optime: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
      optimeDurable: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
      optimeDate: ISODate('2023-12-20T10:00:17.000Z'),
      optimeDurableDate: ISODate('2023-12-20T10:00:17.000Z'),
      lastAppliedWallTime: ISODate('2023-12-20T10:00:17.854Z'),
      lastDurableWallTime: ISODate('2023-12-20T10:00:17.854Z'),
      lastHeartbeat: ISODate('2023-12-20T10:00:19.855Z'),
      lastHeartbeatRecv: ISODate('2023-12-20T10:00:19.855Z'),
      pingMs: Long('0'),
      lastHeartbeatMessage: '',
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1703066087, i: 2 }),
      electionDate: ISODate('2023-12-20T09:54:47.000Z'),
      configVersion: 8,
      configTerm: 3
    },
    {
      _id: 2,
      name: 'mongo2:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 1561,
      optime: { ts: Timestamp({ t: 1703066417, i: 1 }), t: Long('3') },
      optimeDate: ISODate('2023-12-20T10:00:17.000Z'),
      lastAppliedWallTime: ISODate('2023-12-20T10:00:17.854Z'),
      lastDurableWallTime: ISODate('2023-12-20T10:00:17.854Z'),
      syncSourceHost: 'mongo3:27017',
      syncSourceId: 1,
      infoMessage: '',
      configVersion: 8,
      configTerm: 3,
      self: true,
      lastHeartbeatMessage: ''
    }
  ],
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1703066417, i: 1 }),
    signature: {
      hash: Binary.createFromBase64('nZ9+NYoUp/of3M2/+crzQKNbu8g=', 0),
      keyId: Long('7314607631853682693')
    }
  },
  operationTime: Timestamp({ t: 1703066417, i: 1 })
}
```

Said that, I will close the issue because your doubts are related to MongoDB configuration, not with the Bitnami container. Please go to the official upstream channels.

**Closed** 2023-12-20 10:10 UTC
Labels: in-progress, tech-issues, mongodb
