### ISSUE TITLE
[bitnami/redis] container crashed when docker run on arm64

### ISSUE THREAD

**Issue by github87154408** [bitnami/containers#26062] opened 2023-03-02 10:59 UTC
### Name and Version

bitnami/redis:7.0/6.2/5.0/6.0.9-debian-10-r66/7.0.9-*

### What architecture are you using?

arm64

### What steps will reproduce the bug?
```
docker run -it -e ALLOW_EMPTY_PASSWORD=yes docker.io/bitnami/redis:7.0
```
### What is the expected behavior?

container running successfully.

### What do you see instead?
```console
$ docker run -it -e ALLOW_EMPTY_PASSWORD=yes docker.io/bitnami/redis:7.0 
redis 10:35:43.97 
redis 10:35:43.97 Welcome to the Bitnami redis container
redis 10:35:43.98 Subscribe to project updates by watching https://github.com/bitnami/containers
redis 10:35:43.98 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 10:35:43.98 
redis 10:35:43.98 INFO  ==> ** Starting Redis setup **
redis 10:35:44.00 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 10:35:44.01 INFO  ==> Initializing Redis
redis 10:35:44.03 INFO  ==> Setting Redis config file
redis 10:35:44.07 INFO  ==> ** Redis setup finished! **

redis 10:35:44.09 INFO  ==> ** Starting Redis **
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

```console
$ docker run -it -e ALLOW_EMPTY_PASSWORD=yes docker.io/bitnami/redis:6.2
standard_init_linux.go:211: exec user process caused "exec format error"
```
### Additional information

my machine is aarch64.

after failed with above tags. I go through the docker build with https://github.com/bitnami/containers/blob/main/bitnami/redis/7.0/debian-11/Dockerfile
it seems the Dockerfile is under amd64, so i changed the orch from -amd64 to -arm64. 
I got the error :
```
postunpack.sh: 7: set: Illegal option -o pipefail
```
Can someone help to look at it? thanks.

**Comment by javsalgar** [comment] 2023-03-03 09:20
Hi,

In order to change the arch in the Dockerfile, did you modify the file, or you set the `TARGETARCH` arg?

**Comment by github87154408** [comment] 2023-03-09 07:47
Hi  

In the Dockerfile, set the arg OS_ARCH=arm64.

**Comment by lwj5** [comment] 2023-06-18 16:30
Please reopen this issue as it still persists

This issue has been resolved in the official Redis container but not on Bitnami
Please see issue https://github.com/docker-library/redis/issues/208 and fix https://github.com/docker-library/redis/pull/254

Hopefully someone from Bitnami can port the fix over

**Comment by mdhont** [comment] 2023-06-21 15:06
Unfortunately I haven't been able to reproduce the issue, could you give more information? On which machine are you running docker, are you building the image or just pulling and running it?

**Comment by wyzssw** [comment] 2023-06-26 08:23
> Unfortunately I haven't been able to reproduce the issue, could you give more information? On which machine are you running docker, are you building the image or just pulling and running it?


```
➜  ~ getConf PAGE_SIZE
65536
```
Find an arm64 arch node with page-size = 64K NOT 4K

```
docker run -it  bitnami/redis-cluster:latest  -e ALLOW_EMPTY_PASSWORD=yes REDIS_NODES=127.0.0.1:6379  --platform linux/arm64 
```

```
docker run -it  bitnami/redis:latest  --platform linux/arm64 
```

Then will see the error log
```
redis 10:35:44.09 INFO  ==> ** Starting Redis **
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

**Comment by wyzssw** [comment] 2023-06-26 08:34
> @wyzssw Thanks for replying to this, it slipped my mind. You can find such a system on Oracle Cloud ARM servers. We are using the Oracle-managed Kubernetes, installing Redis from Bitnami/Redis chart

Could you please  compile a mirror of bitnami in this 64k page size arm environment? We use bitnami/redis-cluster and bitnami/redis on ours customers self-built cluster but not cluod environment.

The Official image `https://hub.docker.com/_/redis` doesn't have this problem. But https://downloads.bitnami.com/files/stacksmith/redis-7.0.11-1-linux-arm64-debian-11.tar.gz have.

**Comment by lwj5** [comment] 2023-06-26 08:36
@wyzssw my reply was directed to @mdhont. Apologies if there was a misunderstanding

**Comment by wyzssw** [comment] 2023-06-26 08:43
> @wyzssw my reply was directed to @mdhont. Apologies if there was a misunderstanding

Thank you very much

**Comment by networkhermit** [comment] 2023-06-29 10:47
hi, I got the same error when using redis helm chart in arm64 machine with 64K page size.

```text
$ getconf PAGE_SIZE
65536
```

bitnami/redis:7.0.11-debian-11-r24
```text
$ redis-server
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Segmentation fault (core dumped)
```

redis:7.0.11-bookworm

```text
# redis-server
11:C 29 Jun 2023 10:40:52.192 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
11:C 29 Jun 2023 10:40:52.192 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=11, just started
11:C 29 Jun 2023 10:40:52.192 # Configuration loaded
11:M 29 Jun 2023 10:40:52.193 * monotonic clock: POSIX clock_gettime
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 7.0.11 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 11
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

```

**Comment by wyzssw** [comment] 2023-07-10 03:53
@lwj5 @mdhont When will the new image appear。
Could you provide the dockerfile of redis-sentinel，I compile it myself

**Comment by mdhont** [comment] 2023-07-11 13:35
I've created a task for investigating it further. We will notify you in this PR when there is any news.

**Comment by lwj5** [comment] 2023-08-11 01:25
Not stale

**Comment by lwj5** [comment] 2023-09-01 02:30
Not stale

**Comment by aoterolorenzo** [comment] 2023-09-05 13:03
@github87154408, @lwj5 are you still experiencing this issues?

It is now working for me in the, at least, the last revision:

```
docker run -it -e ALLOW_EMPTY_PASSWORD=yes docker.io/bitnami/redis:7.0
redis 12:59:49.24 
redis 12:59:49.24 Welcome to the Bitnami redis container
redis 12:59:49.24 Subscribe to project updates by watching https://github.com/bitnami/containers
redis 12:59:49.25 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 12:59:49.25 
redis 12:59:49.25 INFO  ==> ** Starting Redis setup **
redis 12:59:49.26 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 12:59:49.27 INFO  ==> Initializing Redis
redis 12:59:49.28 INFO  ==> Setting Redis config file
redis 12:59:49.31 INFO  ==> ** Redis setup finished! **

redis 12:59:49.32 INFO  ==> ** Starting Redis **
1:C 05 Sep 2023 12:59:49.345 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 05 Sep 2023 12:59:49.345 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 05 Sep 2023 12:59:49.345 # Configuration loaded
1:M 05 Sep 2023 12:59:49.345 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 7.0.11 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 05 Sep 2023 12:59:49.347 # Server initialized
1:M 05 Sep 2023 12:59:49.352 * Creating AOF base file appendonly.aof.1.base.rdb on server start
1:M 05 Sep 2023 12:59:49.355 * Creating AOF incr file appendonly.aof.1.incr.aof on server start
1:M 05 Sep 2023 12:59:49.355 * Ready to accept connections
```

Working of course in ARM64 (Mac M1)

**Comment by networkhermit** [comment] 2023-09-06 02:04
The latest revision is still not working.

```text
# getconf PAGE_SIZE
65536
#  docker run -it -e ALLOW_EMPTY_PASSWORD=yes docker.io/bitnami/redis:7.0
Unable to find image 'bitnami/redis:7.0' locally
7.0: Pulling from bitnami/redis
90bbff79ced3: Pull complete
Digest: sha256:275eb1f1326560d548708d05f760fc7f4c674c654f68c0dd2a108f50edcda8bd
Status: Downloaded newer image for bitnami/redis:7.0
redis 01:58:00.37
redis 01:58:00.37 Welcome to the Bitnami redis container
redis 01:58:00.37 Subscribe to project updates by watching https://github.com/bitnami/containers
redis 01:58:00.37 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 01:58:00.37
redis 01:58:00.37 INFO  ==> ** Starting Redis setup **
redis 01:58:00.39 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 01:58:00.39 INFO  ==> Initializing Redis
redis 01:58:00.40 INFO  ==> Setting Redis config file
redis 01:58:00.43 INFO  ==> ** Redis setup finished! **

redis 01:58:00.44 INFO  ==> ** Starting Redis **
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

**Comment by wyzssw** [comment] 2023-09-15 03:32
@aoterolorenzo ARM64 (Mac M1) pageSize is 4096，but not 65536

**Comment by aoterolorenzo** [comment] 2023-09-18 10:48
@wyzssw we are working in the fix. It is not trivial, since we cannot exactly reproduce the upstream fix due to the nature of our pipelines, but reproduce it in our compilation step. We will reach back here as soon as it be done.

**Comment by alexandreroman** [comment] 2023-11-28 14:23
Using version 7.2.3-debian-11-r1: same error when running on Raspberry Pi 5 (Raspbian).

**Comment by Pom-Veerawat** [comment] 2024-02-07 03:31
> Using version 7.2.3-debian-11-r1: same error when running on Raspberry Pi 5 (Raspbian).

i have same issue

**Comment by Pom-Veerawat** [comment] 2024-02-07 05:54
is it possible to force setting in this docker ?

https://github.com/bitnami/containers/tree/main/bitnami/redis/7.2/debian-11

**Comment by hollanbm** [comment] 2024-02-07 06:02
> is it possible to force setting in this docker ?
> 
> 
> 
> https://github.com/bitnami/containers/tree/main/bitnami/redis/7.2/debian-11

It's an issue with the build system, and large page sizes

**Comment by Pom-Veerawat** [comment] 2024-02-07 07:01
I solved this issue with 
docker pull redis:latest instead

**Comment by hollanbm** [comment] 2024-02-07 07:20
> I solved this issue with 
> 
> docker pull redis:latest instead 

Yeah, you can use the official redis images. Since those support the large page size.

But the bitnami images, don't. Hence this issue

**Comment by hollanbm** [comment] 2024-02-23 01:23
Not stale

**Comment by aoterolorenzo** [comment] 2024-02-26 16:16
Hi,

I think it makes sense to take a look in order to add support to a larger page size. I will create an internal task for the team to investigate the issue and work in a fix. We will reach you back here as soon our workload allow us to take this forward.

**Comment by yuyihan666** [comment] 2024-04-01 09:10
arm64 7.2-debian-12 <jemalloc>: Unsupported system page size

**Comment by huangyb520** [comment] 2024-04-10 07:09
Same Error

edis 03:22:00.28 INFO  ==> Initializing Redis
redis 03:22:00.29 INFO  ==> Setting Redis config file
redis 03:22:00.31 INFO  ==> ** Redis setup finished! **

redis 03:22:00.32 INFO  ==> ** Starting Redis **
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size

**Comment by fmulero** [comment] 2024-04-11 08:56
Hi

I've just landed in this issue and I think we lost the basics (but please amend me if I am wrong).

Page size and THP (transparent huge pages) are host related configs inherited by the Docker engine. A container can not change the memory page size or the THP unless it is running in privilege mode, which is a very bad idea and the Bitnami containers don't not support it. So the solution will require to config those properties in your host (or in the Docker VM in the case of Mac)

Please take a look to this [issue](https://github.com/docker-library/redis/issues/55) where you can find more information about this problem.

**Comment by networkhermit** [comment] 2024-04-11 13:29
> Hi
> 
> I've just landed in this issue and I think we lost the basics (but please amend me if I am wrong).
> 
> Page size and THP (transparent huge pages) are host related configs inherited by the Docker engine. A container can not change the memory page size or the THP unless it is running in privilege mode, which is a very bad idea and the Bitnami containers don't not support it. So the solution will require to config those properties in your host (or in the Docker VM in the case of Mac)
> 
> Please take a look to this [issue](https://github.com/docker-library/redis/issues/55) where you can find more information about this problem.

I don't think they are the same thing. As the official redis image is working without running in privilege mode:

https://github.com/bitnami/containers/issues/26062#issuecomment-1612863640, https://github.com/bitnami/containers/issues/26062#issuecomment-1707539503

**Comment by fmulero** [comment] 2024-04-12 07:54
I'll try to run some example in a different machine, bear with me. In my case the error is related to TPH (not the error described in the issue) but consistent in both images:

```console
$ docker run --platform="linux/arm64" -it redis:7.0
1:C 12 Apr 2024 07:43:46.671 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 12 Apr 2024 07:43:46.675 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 12 Apr 2024 07:43:46.676 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 12 Apr 2024 07:43:46.683 * monotonic clock: POSIX clock_gettime
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 7.0.15 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 12 Apr 2024 07:43:46.711 # Server initialized
1:M 12 Apr 2024 07:43:46.712 # WARNING You have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 12 Apr 2024 07:43:46.764 # WARNING Your kernel has a bug that could lead to data corruption during background save. Please upgrade to the latest stable kernel.
1:M 12 Apr 2024 07:43:46.764 # Redis will now exit to prevent data corruption. Note that it is possible to suppress this warning by setting the following config: ignore-warnings ARM64-COW-BUG

$ docker run --platform="linux/arm64" -it -e ALLOW_EMPTY_PASSWORD=yes -e BITNAMI_DEBUG=true bitnami/redis:7.0
redis 07:47:31.83 INFO  ==>
redis 07:47:31.90 INFO  ==> Welcome to the Bitnami redis container
redis 07:47:31.95 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis 07:47:31.99 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 07:47:32.03 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
redis 07:47:32.08 INFO  ==>
redis 07:47:32.19 DEBUG ==> Copying files from /opt/bitnami/redis/etc.default to /opt/bitnami/redis/etc
redis 07:47:32.29 INFO  ==> ** Starting Redis setup **
redis 07:47:33.05 DEBUG ==> Validating settings in REDIS_* env vars..
redis 07:47:33.10 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 07:47:33.41 INFO  ==> Initializing Redis
redis 07:47:33.48 DEBUG ==> Ensuring expected directories/files exist
redis 07:47:33.88 INFO  ==> Setting Redis config file
redis 07:47:34.45 INFO  ==> ** Redis setup finished! **

redis 07:47:34.65 INFO  ==> ** Starting Redis **
1:C 12 Apr 2024 07:47:34.869 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 12 Apr 2024 07:47:34.873 # Redis version=7.0.15, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 12 Apr 2024 07:47:34.873 # Configuration loaded
1:M 12 Apr 2024 07:47:34.879 * monotonic clock: POSIX clock_gettime
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 7.0.15 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 12 Apr 2024 07:47:34.909 # Server initialized
1:M 12 Apr 2024 07:47:34.910 # WARNING You have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 12 Apr 2024 07:47:34.930 # WARNING Your kernel has a bug that could lead to data corruption during background save. Please upgrade to the latest stable kernel.
1:M 12 Apr 2024 07:47:34.930 # Redis will now exit to prevent data corruption. Note that it is possible to suppress this warning by setting the following config: ignore-warnings ARM64-COW-BUG

**Comment by fmulero** [comment] 2024-04-12 09:34
Hi @networkhemit Could you share more details about the instance where you are facing the issue? I tried different instances without luck 😞

**Comment by networkhermit** [comment] 2024-04-12 10:12
> Hi @networkhemit Could you share more details about the instance where you are facing the issue? I tried different instances without luck 😞

Do you have access to arm64 linux machine with 64K page size?

You can verify the page size as following:
```console
$ getconf PAGE_SIZE
65536
```

I don't know if this issue can be emulated by qemu or docker.

I noticed previous comment in https://github.com/bitnami/containers/issues/26062#issuecomment-1606959059 mentioned that Oracle have arm64 linux box with 64K page size. Maybe you can create a free instance there.

**Comment by fmulero** [comment] 2024-04-16 10:12
Hi, I've just reproduced the issue using a `t4g.medium` AWS instance  and [ubuntu with the 64k kernel](https://ubuntu.com/server/docs/choosing-between-the-arm64-and-arm64-largemem-installer-options).

This error was [fixed in the oficial image](https://github.com/docker-library/redis/pull/254) changing jemalloc compilation flags.

**Comment by bienchen** [comment] 2024-04-18 18:56
I have the same issue on Raspberry Pi 5/ latest Raspberry Pi OS.

**Comment by fmulero** [comment] 2024-04-19 07:42
I am happy to announce that following tags should fix (🤞) this issue:
* 7.2.4-debian-12-r12
* 7.0.15-debian-12-r13
* 6.2.14-debian-12-r16

You won't see any clue about the fix in the container code because new compilation flags were required to fix it. From now on Redis is compiled with `JEMALLOC_CONFIGURE_OPTS = '--with-lg-page=16 --with-lg-hugepage=21'`

**Comment by VNovotna** [comment] 2024-04-19 07:53
Confirming that using `7.2.4-debian-12-r12` the issue is fixed for me on RPi 5 / Raspberry Pi OS.

**Comment by bienchen** [comment] 2024-04-20 16:45
`7.2.4-debian-12-r12` also works for me!

**Comment by fmulero** [comment] 2024-04-22 06:22
Great! Thanks a lot for checking it. I think that I can close this issue, woop woop!

**Comment by jinjianming** [comment] 2024-04-26 09:35
@fmulero  6.2.14 still unsuccessful, 7. x is successful
```
[root@localhost jenkins]# getconf PAGESIZE
65536
[root@localhost jenkins]# docker run -e ALLOW_EMPTY_PASSWORD=yes -it  bitnami/redis:6.2.14-debian-12-r17
redis 09:33:49.17 INFO  ==> 
redis 09:33:49.17 INFO  ==> Welcome to the Bitnami redis container
redis 09:33:49.18 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis 09:33:49.18 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 09:33:49.18 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
redis 09:33:49.18 INFO  ==> 
redis 09:33:49.18 INFO  ==> ** Starting Redis setup **
redis 09:33:49.21 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 09:33:49.21 INFO  ==> Initializing Redis
redis 09:33:49.23 INFO  ==> Setting Redis config file
redis 09:33:49.26 INFO  ==> ** Redis setup finished! **

redis 09:33:49.29 INFO  ==> ** Starting Redis **
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
[root@localhost jenkins]# docker run -e ALLOW_EMPTY_PASSWORD=yes -it  bitnami/redis:6.2.14-debian-12-r16
redis 09:33:55.87 INFO  ==> 
redis 09:33:55.87 INFO  ==> Welcome to the Bitnami redis container
redis 09:33:55.87 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
redis 09:33:55.87 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis 09:33:55.88 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
redis 09:33:55.88 INFO  ==> 
redis 09:33:55.88 INFO  ==> ** Starting Redis setup **
redis 09:33:55.91 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 09:33:55.91 INFO  ==> Initializing Redis
redis 09:33:55.92 INFO  ==> Setting Redis config file
redis 09:33:55.96 INFO  ==> ** Redis setup finished! **

redis 09:33:55.98 INFO  ==> ** Starting Redis **
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
```

**Comment by jinjianming** [comment] 2024-04-26 09:41
open issues

**Comment by carrodher** [comment] 2024-12-18 10:54
Redis container image is now multi arch.

**Closed by carrodher** 2024-12-18 10:54 UTC
Labels: on-hold, tech-issues, redis
