### ISSUE TITLE
[bitnami/kafka] No Broker Log output into file

### ISSUE THREAD

**Issue by yitian108** [bitnami/containers#53270] opened 2023-11-28 15:02 UTC
### Name and Version

bitnami/kafka:3.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.  deploy the bitnami/kafka:3.6 as the image with k8s in node1
2. deploy the bitnami/kafka:2.5 as the image with k8s in node2
3. using the command `kubectl logs -n <ns> <kafka-pod>`, both node1 & node2 can print server log normally
4. while for kafka:3.6 which locates in node1, the inner container in kafka pod did not output any file in the directory /opt/bitnami/kafka/logs/, for kafka:3.5 which locates in node2, the inner container in kafka pod did output files in the directory /opt/bitnami/kafka/logs/.

### What is the expected behavior?

Both nodes should output the broker logs to the directory in the container, but the new version 3.6 did not

### What do you see instead?

there is no log in the container's directory /opt/bitnami/kafka/logs

### Additional information

I can reproduce the case in one centos server, only need to replace the image of kafka in yaml, as a result, the old version 2.5 can output the server log, the new version 3.6 do not.

**Comment by yitian108** [comment] 2023-12-06 01:17
@hjdjoo, It looks like the other issue. What I mentioned above is about the server's log, which is usually located in the directory /opt/bitnami/kafka/logs. However, you may mean the data log, which contains the topic and partition data. We may have different issues.

**Comment by yitian108** [comment] 2023-12-19 06:42
@carrodher, @fevisera anyupdate? This broker log is very important for us, we may roll the log mechanism or compact the history log file to reduce disk consumption.

**Comment by yitian108** [comment] 2024-01-04 11:29
Hello, @carrodher, @fevisera  ?

**Comment by fevisera** [comment] 2024-01-11 11:33
Hi @yitian108,

Sorry for the delay. By default, our containers put all the logs in /dev/stdout following the 12-factor container principles. A similar question was asked for another application on https://github.com/bitnami/charts/issues/14461#issuecomment-1398130420.

`bitnami/kafka:2.5` is not listed in https://github.com/bitnami/containers/tree/main/bitnami/kafka so it is not being supported.

**Comment by yitian108** [comment] 2024-01-12 08:46
Hi @fevisera , 

Thank you for your reply. I understand if the container follows the 12-factor principles, the logs will be put in /dev/stdout. Is there any other way that I can access the logs, which are output in /dev/stdout, except using the EFK stack or the LGTM stack?

Alternatively, is there another version of bitnami/kafka, around version 3.6, that can be used with log output inside the container by default?

**Comment by fevisera** [comment] 2024-01-29 10:21
Hi @yitian108,

Have you had the opportunity to review the logging section in the Readme at https://github.com/bitnami/containers/tree/main/bitnami/kafka#logging? This section outlines an alternative option for accessing the logs. I hope it proves to be suitable for your needs.

**Comment by yitian108** [comment] 2024-01-30 08:26
Hi @fevisera , thank you. It looks good for setting the logging driver. To my understanding, it should configure some Docker configurations. However, there is no Docker on the server since we only deploy Kubernetes, and Docker may not be necessary for us to install. I will try to find another way to solve this problem.

Thank you again!

**Comment by fevisera** [comment] 2024-01-30 11:13
Hi @yitian108,

If configuring the logging driver proves challenging, an alternative approach might involve adjusting the parameters of the existing image. For instance, you can find lines in the code that disable logging at this GitHub repository link: https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.6/debian-11/rootfs/opt/bitnami/scripts/kafka/postunpack.sh#L36-L46

However, it is important to note that we do not recommend this method, as it may lead to potential container size issues. Please consider this information in your troubleshooting process.

As the issue is closely tied to the application's configuration, and considering we have discussed a few available options for addressing it, I will proceed to close this issue. 

Thank you.

**Closed by fevisera** 2024-01-30 11:13 UTC
Labels: in-progress, tech-issues, kafka
