### ISSUE TITLE
[bitnami/moodle] SSL bug with latest moodle4.1

### ISSUE THREAD

**Issue by bespokeeagle** [bitnami/containers#70370] opened 2024-07-25 14:51 UTC
### Name and Version

bitnami/moodle

### What architecture are you using?

None

### What steps will reproduce the bug?

Pull the latest moodle 4.1
try to connect it to a database

### What is the expected behavior?

there should be no issues connecting

### What do you see instead?

there is an ssl error when attempting to connect to the db

### Additional information

Up until yesterday everything worked just fine we build a custom moodle image from bitnami/moodle 4.1 and it connects to the database without any additional configuration but yesterday we rebuilt the image with the latest 4.1 and we now see this error `ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it`. Reverting/pinning the base image used to bitnami/moodle4.1@16ec6770e8f401930ff7746f24c1462e00874a12431df81624b6ee78f21cfc4d or any commit before works just fine

**Comment by Skyr** [comment] 2024-07-25 18:20
Can confirm, same here, too.
My temporary fix: Create a file "/somewhere/my.cnf" with the content
```
[client]
ssl=off
```
and mount it into the Docker container to /opt/bitnami/mysql/conf/my.cnf (I don't know if the file used to exist here, at the moment it's gone).

**Comment by xorinzor** [comment] 2024-07-29 07:02
Same happens for the Wordpress container

**Comment by XaratosS** [comment] 2024-07-29 09:06
I am having the same issue. Did a Debug of a new container. Here are the logs:

`akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.80 INFO  ==>
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.80 INFO  ==> Welcome to the Bitnami moodle container
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.80 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.81 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.81 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.81 INFO  ==>
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.81 INFO  ==> ** Starting Moodle setup **
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.82 DEBUG ==> Validating settings in APACHE_* environment variables
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.84 DEBUG ==> Copying files from /opt/bitnami/apache/conf.default to /opt/bitnami/apache/conf
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:01.85 INFO  ==> Generating sample certificates
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | Certificate request self-signature ok
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | subject=CN = example.com
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | realpath: /bitnami/apache/conf: No such file or directory
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.05 INFO  ==> Configuring Apache ServerTokens directive
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.06 DEBUG ==> Configuring ServerTokens Prod on file /opt/bitnami/apache/conf/httpd.conf
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.08 INFO  ==> Configuring PHP options
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.09 INFO  ==> Setting PHP expose_php option
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.10 INFO  ==> Setting PHP output_buffering option
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.12 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.13 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.16 DEBUG ==> Validating settings in MOODLE_* environment variables...
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.21 INFO  ==> Ensuring Moodle directories exist
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.32 INFO  ==> Trying to connect to the database server
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:03.32 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:08.33 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:13.35 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:18.36 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:23.37 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:28.39 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:33.40 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:38.41 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:43.42 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:48.44 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:53.45 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:03:58.46 DEBUG ==> Executing SQL command:
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | SELECT 1
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | /opt/bitnami/mysql/bin/mysql: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mysql/bin/mariadb' instead
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | ERROR 2026 (HY000): TLS/SSL error: SSL is required, but the server does not support it
akademie-test_moodle.1.km1w1fov04fn@bvbdockerworker0003    | moodle 09:04:03.47 ERROR ==> Could not connect to the database`

**Comment by MaybeLater945** [comment] 2024-07-29 09:13
Same here, ssl is required with seemingly no option to disable it.

**Comment by XaratosS** [comment] 2024-07-29 09:46
So this also happens on the image version 4.4 and 4.3. So that means, that there is a bigger issue and that it should be fixed as soon as possible. 

We have figure out, that there is a variable, which you can not set. We have tried to set the Variable:
```
MYSQL_CLIENT_ENABLE_SSL=no
```
Sadly this dosnt have the expected result. Please check out, if there is an error or if you can add a variable, where we can disable TLS/SSL to connect to the DB Server

**Comment by XaratosS** [comment] 2024-07-29 10:08
So if you try and start wirh the image 4.4.0 it works without any issues. The installation and conection to the DB works without any issues. @bespokeeagle can you try and use the image 4.4.0? Maybe that works?

**Comment by bespokeeagle** [comment] 2024-07-29 11:19
> So if you try and start wirh the image 4.4.0 it works without any issues. The installation and conection to the DB works without any issues. @bespokeeagle can you try and use the image 4.4.0? Maybe that works?

Yes 4.4.0 seems to work just fine but we have a requirement to stick to 4.1, for now we just use a version before the update

**Comment by XaratosS** [comment] 2024-07-29 11:50
> > So if you try and start wirh the image 4.4.0 it works without any issues. The installation and conection to the DB works without any issues. @bespokeeagle can you try and use the image 4.4.0? Maybe that works?
> 
> @XaratosS Yes 4.4.0 seems to work just fine but we have a requirement to stick to 4.1, for now we just use a version before the update

I was just wondering if you run into the same issue as I ran into. Basically what happens is, that SSL/TLS tries to connect to the DB and I assume, that you dont have SSL/TLS configured for your DB Server. Technically the solution should be to set up SSL/TLS on your server. If you dont have the possibility to do that, we should have the option to disable SSL/TLS

**Comment by juan131** [comment] 2024-08-01 07:13
Duplicate of https://github.com/bitnami/containers/issues/70006, please let's continue the conversation there

**Closed by juan131** 2024-08-01 07:13 UTC
Labels: in-progress, tech-issues, moodle
