### ISSUE TITLE
[bitnami/keycloak] Failed to update database, Failed to add realm code secret

### ISSUE THREAD

**Issue by clickersmudge** [bitnami/containers#63443] opened 2024-02-28 19:30 UTC
### Name and Version

helm bitnami/keycloak --version 18.7.1

### What architecture are you using?

None

### What steps will reproduce the bug?

Hi,
We are building a Keycloak image (https://github.com/bitnami/containers/tree/main/bitnami/keycloak). We are using the CockroachDB database. Keycloak was working fine until the upgrade. Currently there is an error on startup.
It does not work after the upgrade it also does not work on a clean database.

![Zrzut ekranu z 2024-02-28 20-26-58](https://github.com/bitnami/containers/assets/113194014/25a20996-b1e9-404f-86d3-25de1f2ce75a)

```
2024-02-28 18:46:10,562 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com:

     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com:

     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com:

     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: column "code_secret" does not exist

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

We are debugging, but we cannot deal with the problem.

### What do you see instead?

```
2024-02-28 18:46:10,562 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com:

     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,630 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com:

     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-1.1.0.Beta1.xml::1.1.0.Beta1::sthorger@redhat.com:

     Reason: liquibase.exception.UnexpectedLiquibaseException: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.CustomChangeException: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to add realm code secret

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ERROR: column "code_secret" does not exist

2024-02-28 18:46:10,631 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```

**Comment by javsalgar** [comment] 2024-02-29 09:13
Hi!

Could you let us know which values you are using to deploy the chart? We would like to reproduce it on our side

**Comment by javsalgar** [comment] 2024-02-29 09:14
Closing this as duplicate of https://github.com/bitnami/charts/issues/23970

**Closed by javsalgar** 2024-02-29 09:14 UTC
Labels: tech-issues, triage, keycloak
