### ISSUE TITLE
[bitnami/discourse] Upgraded to 3.0.1 image and now site is broken

### ISSUE THREAD

**Issue by stevejr** [bitnami/containers#24145] opened 2023-02-16 13:37 UTC
### Name and Version

bitnami/discourse:3.0.1

### What steps will reproduce the bug?

Raised issue in https://github.com/bitnami/charts/issues/14913 aswell as did not know which project it should be in

Upgraded Helm Chart from version 8.1.8 to 10.0.0 which also upgrades the image to 3.0.1 and now the site is broken.

In Safari we see the below error and cannot access the site in safe-mode:

```
Error: Could not find module `handlebars` imported from `discourse-common/lib/raw-handlebars`
```

In Chrome we see the below error but can access the site in safe-mode if we disable all plugins:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_tippy')
```

Any help would be greatly appreciated

### What is the expected behavior?

Site should be accessible and load correctly after upgrade to 3.0.1

### What do you see instead?

The site will not load.

Debugging the error in Chrome seems to imply an issue with the use of tippy when loading the `/categories` endpoint.

**Comment by stevejr** [comment] 2023-02-16 15:08
The issue with Chrome browser appears to be the `discourse-local-dates` plugin. When the feature `discourse local dates enabled` is enabled in Discourse the tippy error occurs. As soon as it is disabled the site will load.

**Comment by carrodher** [comment] 2023-02-16 15:14
Closed as duplicate of https://github.com/bitnami/charts/issues/14913

**Closed by carrodher** 2023-02-16 15:14 UTC
Labels: tech-issues, triage
